<?php
declare(strict_types=1);
/**
 * All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block GingerPay\Payment\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-ginger">
    <p>
        <?= $block->escapeHtml(__('Xpate is a payments platform for e-commerce businesses that helps with cashflow problem.')) ?>
    </p>
    <table>
        <tbody>
            <tr>
                <td>
                    <?= $block->escapeHtml(__('Visit xpate.com')) ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>
